#!/bin/bash
#################################################################
#   Rotary Random Password Generator                            #
#                     By Robert D. Wei (Freedman) 2015 Nov.     #
#                                               License: GPL 2  #
#################################################################
readonly SysMax=2147483647
readonly OneMinuteCounts=100000000
readonly LowerCaseLetters='abcdefghijklmnopqrstuvwxyz'
readonly UpperCaseLetters='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
readonly Numbers='0123456789'
readonly Symbles='!"#$%&'"'"'()*+,-./:;<=>?@[\]^_`{|}~'
BOARD_color=""
BOARD_lnth=8
BOARD_candidStr=""
BOARD_ezmod=""
BOARD_auto=""
BOARD_chrCmp=""
BOARD_engineer=""





case $LANG in
  zh_TW*)
    readonly _all_candidate_characters_are='候選字元：'
    readonly _rotor_size='轉輪大小：'
    readonly _slow_down_please='請減慢速度！'
    readonly _character='字元'
    readonly _rounds='轉'
    readonly _help_page="$( (while read ; do echo "$REPLY" ; done) <<- EOF
	*** 轉輪式隨機密碼產生器 ***

	請用 "$0 [-a] [-c|-n] [密碼長度] [l][u][n][s] [-s ...]"
	    l:  小寫字母     u:  大寫字母
	    n:  數字　　     s:  其他符號    ( 預設值： luns )
	    -e:  簡易模式，使用 'lsunln' 作為候選符號的組合方式
	    -a:  自動產生密碼，以 /dev/random 作為隨機來源 ( 不建議使用！ )
	    -c/n:  彩色輸出 / 不使用彩色 ( 預設值： n )
	    -s:  將接下來的字串作為候選符號

	每按一次 '[Enter]' 產生一個隨機符號。

	註：準備好以後，執行本程式並取得密碼。＊不要＊為了不重要的理由，就重新
	　　再取一次密碼。過度篩選密碼會使得密碼變得可以預測。例如，如果每十個
	　　密碼裡，有九個因為太難記住而廢棄，那麼所有可能的密碼組合中，只有十
	　　分之一可能真正使用。瞭解這一點的攻擊者，在猜密碼的時候速度可以加快
	　　為十倍。
	　－－好記的密碼不好用，好用的密碼不好記－－
	EOF
	)"
    readonly _error_message="$( (while read ; do echo "$REPLY" ; done) <<- EOF
	請用 "$0 [-a] [-c|-n] [密碼長度] [l][u][n][s] [-s ...]"

	　或輸入 "$0 -h|--help" 取得說明
	EOF
	)"
    ;;


  *)
    readonly _all_candidate_characters_are='All candidate characters are:'
    readonly _rotor_size='Rotor size:'
    readonly _slow_down_please='Slow down, please!'
    readonly _character='Character'
    readonly _rounds='Rounds'
    readonly _help_page="$( (while read ; do echo "$REPLY" ; done) <<- EOF
	*** Rotary Random Password Generator ***

	Use "$0 [-a] [-c|-n] [length of password] [l][u][n][s] [-s ...]"
	    l:  lowercase   u:  uppercase
	    n:  numbers     s:  other symbol    ( default:  luns )
	    -e:  easy mode, use 'lsunln' as the composition of the candidates
	    -a:  auto generate from /dev/random ( NOT RECOMMENDED! )
	    -c/n:  color / no color ( default: n )
	    -s:  use the following string as candidates

	Press '[Enter]' and generate one random character each time.

	Note:  Prepare yourself, then execute this program and get the password.
	       DO NOT re-generate a password for some unimportant reasons.
	       Over filtering will turn your random password predictable.  For
	       example, throwing away nine passwords from ten only because
	       they are too hard to remember, then only 10% of all possible
	       passwords will be use.  An attacker may speed up ten times
	       on guessing it by knowing that.
	 -- Easy passwords aren't strong, strong passwords aren't easy. --
	EOF
	)"
    readonly _error_message="$( (while read ; do echo "$REPLY" ; done) <<- EOF
	Use "$0 [-a] [-c|-n] [length of password] [l][u][n][s] [-s ...]"

	   or "$0 -h|--help" for help.
	EOF
	)"
    ;;
esac





function integer_large_enough() {
  declare -i bigInt=1

  while [ $bigInt -lt $(( bigInt *2 )) ] ; do
    bigInt=bigInt*2
  done

  test $(( $bigInt / $OneMinuteCounts )) -gt 1440
  return $?
}


function err_out() {
  echo
  echo "$_error_message"
  echo
  exit $1
}


function analysis_arguments() {
  declare -i cnt
  local arg

  ### Special arguments ###
  if [ "$#" == "1" ] && [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then
    echo
    echo "$_help_page"
    echo
    exit 0
  fi

  if [ "$1" == "engineer" ] || [ "$1" == "programer" ]; then
    BOARD_engineer="1"
    BOARD_color="1"
    BOARD_lnth=12
    shift
  fi

  ### regular arguments ###
  while [ "$1" != "" ] ; do

    #### is length ####
    arg=$1
    while [ "$arg" != "${arg#[0-9]}" ] ; do arg="${arg#[0-9]}" ; done
    if [ "$arg" == "" ] ; then
      BOARD_lnth="$1"
      shift
      continue
    fi

    #### is composition of candidates ####
    arg=$1
    while [ "$arg" != "${arg#[luns]}" ] ; do arg="${arg#[luns]}" ; done
    if [ -z "$arg" ] ; then
      BOARD_chrCmp+=$1
      shift
      continue
    fi

    #### is candidate character string ####
    if [ "$1" == "-s" ] && [ -n "$2" ] ; then
      BOARD_candidStr+="$2"
      shift 2
      continue
    fi

    #### is other parameters ####
    if [ "${1:0:1}" = "-" ] && [ ${#1} -gt 1 ] ; then
      for ((cnt=1; cnt<${#1}; cnt++)) ; do
        case "${1:$cnt:1}" in
          "e")  BOARD_ezmod="1"  ;;
          "a")  BOARD_auto="1"   ;;
          "c")  BOARD_color="1"  ;;
          "n")  BOARD_color=""   ;;
          *)    err_out 1   ;;
        esac
      done
      shift
      continue
    fi

    err_out 1

  done
}


function candidate_characters() {
  local rotor="$BOARD_candidStr"

  if [ -n "$BOARD_ezmod" ] ; then
    BOARD_chrCmp+="lsunln"
  fi

  if [ -z "$BOARD_chrCmp" ] && [ -z "$rotor" ] ; then
    BOARD_chrCmp="luns"
  fi

  for ((n=0; n<${#BOARD_chrCmp}; n++)) ; do
    case "${BOARD_chrCmp:$n:1}" in
      "l")  rotor+="$LowerCaseLetters"  ;;
      "u")  rotor+="$UpperCaseLetters"  ;;
      "n")  rotor+="$Numbers"   ;;
      "s")  rotor+="$Symbles"  ;;
    esac
  done

  echo "$rotor"
}


function generatePasswd_monitorOn3() {

  if [ -z "$BOARD_auto" ] ; then
    manualGenerate_monitorOn3 "$@"
  else
    auto_generate "$@"
  fi
}

function manualGenerate_monitorOn3() {
  local rotor="$1"
  declare -i cnt rotrSiz=${#rotor} wndow=0
  declare -i wndoBndry=${SysMax}-${SysMax}%rotrSiz
  local minStep=$(( $rotrSiz * 100 ))
  local rndPaswd

  if integer_large_enough ; then
    local integerLargeEnough=true
  else
    local integerLargeEnough=false
  fi

  if [ -n "$BOARD_engineer" ]  ; then
    echo >&3
    echo "$_all_candidate_characters_are" >&3
    echo "$rotor" >&3
    echo >&3
    echo "$_rotor_size  $rotrSiz" >&3
    echo >&3
  fi

  for ((cnt=1; cnt<=$BOARD_lnth; cnt++)) ; do

    if $integerLargeEnough ; then
      until read -t 0 ; do
          wndow=wndow+1
      done
      read
    else
      until read -t 0 ; do
          wndow=(wndow+1)%wndoBndry
      done
      read
    fi

    if [ -n "$BOARD_engineer" ]  ; then
      echo -e "\E[1A$_character $cnt:  $(($wndow/$rotrSiz)) $_rounds" >&3
    else
      echo -ne '\E[1A\E[K' >&3
      [ $wndow -lt $minStep ] && echo -n "$_slow_down_please"
    fi
    wndow=wndow%rotrSiz
    rndPaswd+="${rotor:$wndow:1}"

  done

  echo -ne '\n\E[1A\E[K' >&3
  echo "$rndPaswd"
}

function auto_generate() {
  local rotor="$1"
  declare -i cnt rotrSiz=${#rotor} wndow
  declare -i unitBndry=1 unitBits=0 rndBits=0 rndDat=0
  local rndPaswd

  while [ $unitBndry -lt $rotrSiz ] ; do
    unitBits=unitBits+1
    unitBndry=unitBndry*2
  done

  for ((cnt=1; cnt<=$BOARD_lnth; cnt++)) ; do
    wndow=rotrSiz
    until [ $wndow -lt $rotrSiz ] ; do
      while [ $rndBits -lt $unitBits ] ; do
        rndDat=rndDat+$(od -A n -i -N 1 /dev/random)*2**rndBits
        rndBits=rndBits+8
      done
      wndow=rndDat%unitBndry
      rndDat=rndDat/unitBndry
      rndBits=rndBits-unitBits
    done
    rndPaswd+="${rotor:$wndow:1}"
  done
  echo "$rndPaswd"
}


function colorize () {
  local string="$1"
  local out='\E[47m'
  local char point

  for ((point=0; point<${#string}; point++)) ; do
    char="${string:$point:1}"
    if [ "${char^}" == "$char" ] && [ "${char,}" != "$char" ] ; then
      if [ "$Running" != "u" ] ; then
        Running=u
        out+='\E[31m'
      fi
      out+="$char"
    elif  [ "${char^}" != "$char" ] && [ "${char,}" == "$char" ] ; then
      if [ "$Running" != "l" ] ; then
        Running=l
        out+='\E[34m'
      fi
      out+="$char"
    else
      if [ "$Running" != "s" ] ; then
        Running=s
        out+='\E[30m'
      fi
      out+="$char"
    fi
  done
  out+='\E[0m'

  echo "$out"
}


function outputPasswd() {
  local rndPaswd="$1"

  if [ -n "$BOARD_color" ] ; then
    echo -e "$( colorize "$rndPaswd" )"
  else
    echo "$rndPaswd"
  fi
}


function main() {
  local rotor rndPaswd

  analysis_arguments "$@"

  rotor="$( candidate_characters )"

  exec 3>&1
  rndPaswd="$( generatePasswd_monitorOn3 "$rotor" )"
  exec 3>&-

  outputPasswd "$rndPaswd"
}


main "$@"
